//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hurricane.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TriggerbotToggleBindName {
            get {
                return ((string)(this["TriggerbotToggleBindName"]));
            }
            set {
                this["TriggerbotToggleBindName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WallhackToggleBindName {
            get {
                return ((string)(this["WallhackToggleBindName"]));
            }
            set {
                this["WallhackToggleBindName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoFlashToggleBindName {
            get {
                return ((string)(this["NoFlashToggleBindName"]));
            }
            set {
                this["NoFlashToggleBindName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BunnyhopBindName {
            get {
                return ((string)(this["BunnyhopBindName"]));
            }
            set {
                this["BunnyhopBindName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int TriggerbotToggleBindKey {
            get {
                return ((int)(this["TriggerbotToggleBindKey"]));
            }
            set {
                this["TriggerbotToggleBindKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WallhackToggleBindKey {
            get {
                return ((int)(this["WallhackToggleBindKey"]));
            }
            set {
                this["WallhackToggleBindKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NoFlashToggleBindKey {
            get {
                return ((int)(this["NoFlashToggleBindKey"]));
            }
            set {
                this["NoFlashToggleBindKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BunnyhopBindKey {
            get {
                return ((int)(this["BunnyhopBindKey"]));
            }
            set {
                this["BunnyhopBindKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowedPistols {
            get {
                return ((bool)(this["AllowedPistols"]));
            }
            set {
                this["AllowedPistols"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowedShotguns {
            get {
                return ((bool)(this["AllowedShotguns"]));
            }
            set {
                this["AllowedShotguns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowedAWP {
            get {
                return ((bool)(this["AllowedAWP"]));
            }
            set {
                this["AllowedAWP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowedRifles {
            get {
                return ((bool)(this["AllowedRifles"]));
            }
            set {
                this["AllowedRifles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowedSMGs {
            get {
                return ((bool)(this["AllowedSMGs"]));
            }
            set {
                this["AllowedSMGs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowedNoobWeapons {
            get {
                return ((bool)(this["AllowedNoobWeapons"]));
            }
            set {
                this["AllowedNoobWeapons"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float RedEnemy {
            get {
                return ((float)(this["RedEnemy"]));
            }
            set {
                this["RedEnemy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GreenEnemy {
            get {
                return ((float)(this["GreenEnemy"]));
            }
            set {
                this["GreenEnemy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float BlueEnemy {
            get {
                return ((float)(this["BlueEnemy"]));
            }
            set {
                this["BlueEnemy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float RedFriend {
            get {
                return ((float)(this["RedFriend"]));
            }
            set {
                this["RedFriend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GreenFriend {
            get {
                return ((float)(this["GreenFriend"]));
            }
            set {
                this["GreenFriend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float BlueFriend {
            get {
                return ((float)(this["BlueFriend"]));
            }
            set {
                this["BlueFriend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FriendlyWallhack {
            get {
                return ((bool)(this["FriendlyWallhack"]));
            }
            set {
                this["FriendlyWallhack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowedAimImprove {
            get {
                return ((bool)(this["AllowedAimImprove"]));
            }
            set {
                this["AllowedAimImprove"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowedSwapWeapon {
            get {
                return ((bool)(this["AllowedSwapWeapon"]));
            }
            set {
                this["AllowedSwapWeapon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowedQuickScope {
            get {
                return ((bool)(this["AllowedQuickScope"]));
            }
            set {
                this["AllowedQuickScope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReactionTime {
            get {
                return ((int)(this["ReactionTime"]));
            }
            set {
                this["ReactionTime"] = value;
            }
        }
    }
}
